library(TMB)
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

library(data.table)
library(worldfootballR)
library(ggplot2)
library(patchwork)
theme_set(theme_bw())